### ISSUE TITLE
Lack some test cases for Proxy/Agent/Mutant contracts

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-contract#31]
# Description

after refactoring of contract test cases, I found we lack some for checking vulnerability of proxy, agent and mutant contracts

# Task list
### current stage
- [x] check transferring of cluster cell
- [x] check transferring of proxy cell
- [x] check burning of proxy cell
- [x] check transferring of agent cell
- [x] check burning of agent cell
- [x] check minting spore from agent

### next stage
- [x] check creation of spore cell with mutant cell
- [ ] check transfer action of spore cell with mutant cell
- [ ] check burning action of spore cell with mutant cell
- [ ] check mutant feature with complex Lua script

**Comment by ashuralyk** [comment]
test cases completed except mutant is here: https://github.com/sporeprotocol/spore-contract/pull/44
