### ISSUE TITLE
Spore contract version management and release publish

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-contract#46]
# Description

We lack version management on Spore contract repository, we have to upload tags information to indicate our previous `v1` version and current `v2` version.

After deployment on CKB mainnet, we also have to publish deployment related information, such as `code_hash`, `tx_hash`, `out_index`, and corresponding contract names, etc.

# Tasks list
- [x] create tag for version v1
- [x] create tag for version v2
- [x] publish deployment information about testnet on README.md
- [x] publish deployment information about mainnet on README.md

**Comment by ashuralyk** [comment]
@Flouse for tagging, do you recommend we use `0.1.0` to represent our version `v1`, and so as to that using `0.2.0` to represent version `v2`?

**Comment by Flouse** [comment]
> @Flouse for tagging, do you recommend we use `0.1.0` to represent our version `v1`, and so as to that using `0.2.0` to represent version `v2`?

Either way, LGTM.


From another perspective, I think it makes sense to use the same version style with [spore-sdk](https://github.com/sporeprotocol/spore-sdk/pull/71).
